name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - "v*"

permissions: {}

jobs:
  build:
    name: tag release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.repository == 'metal3-io/cluster-api-provider-metal3'
    steps:
    - name: Export RELEASE_TAG var
      run: echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
    - name: checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Install go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: '1.22'
    - name: Generate release artifacts and notes
      run: |
        make release
    - name: Release
      uses: softprops/action-gh-release@7b4da11513bf3f43f9999e90eabced41ab8bb048 # v2.2.0
      with:
        draft: true
        files: out/*
        body_path: releasenotes/${{ env.RELEASE_TAG }}.md
